config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :categories

  resources :home do
    collection do
      get 'about'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root :to => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :posts

  # Scopes
  scope :active, -> { where(active: true) }
end

app/models/email_log.rb
class EmailLog < ApplicationRecord
  validates :category, :sent_at, presence: true

  # Last digest timestamp
  def self.last_digest_sent
    EmailLog
      .where(category: 'digest')
      .order('sent_at desc')
       .first
      .sent_at
  end

  # Guard digest from being sent within 24 hours of each other
  def self.digest_can_send?
    EmailLog.last_digest_sent < 24.hours.ago && Post.recent_items.count > 0
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  # Validations
  validates :title, :description, :category_id, :author, :email, presence: true

  # Scopes
  scope :in_category, -> (category) { where(category_id: category.id) }
  scope :most_recent, -> { order('created_at desc') }

  # Return posts since last notification
  def Post.recent_items
    Post.where('created_at > ?', (7.days/Settings.notify_frequency).seconds.ago)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  # Return first and last name
  def full_name
    if self.first_name.present? && self.last_name.present?
      "#{first_name} #{last_name}".better_titlecase
    end
  end

  def self.from_omniauth(auth_token)
    data = auth_token.info
    user = User.where(email: data['email']).first

    # Create user if doesn't exist
    unless user
        user = User.create(
            first_name: data['first_name'],
            last_name: data['last_name'],
            email: data['email'],
            password: Devise.friendly_token[0,20],
            avatar_url: data['image']
        )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    if @category
      @posts = Post.in_category(@category).most_recent.paginate(page: params[:page], per_page: 20)
    else
      redirect_to categories_path, alert: 'Please provide a valid category.'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  # GET /home
  def index
    @categories = Category.includes(:posts).active.all

    respond_to do |format|
      format.html { render :index }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts/1
  # GET /posts/1.json
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:category_id, :title, :description, :author, :email)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  # Required asterik
  def required
    raw('<span class="required">*</span>')
  end

  # Return as new item if date is more than 2 days old
  # Arg: d is a Date object
  # Arg: inline_styled is a Boolean for using inline CSS styles
  def mark_as_new(post_date:, inline_style: false)
    if post_date > (7.days / Settings.notify_frequency).seconds.ago
      return raw('<span style="font-size: 10px; font-weight: bold; color: #ffffff; background-color: #009900; padding: 1px 3px 1px 3px; margin: 0 0 0 4px;">new</span>') if inline_style
      return raw('<span class="new">new</span>')
    end
  end

  # Return a formatted post title
  def post_title(p)
    truncate(p.title, length: 50)
  end
end

app/views/categories/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to @category.name, category_path(@category) %></li>
</ol>


<h1><%= @category.name %></h1>

<div class="buttons">
  <%= link_to 'Add a Post', new_post_path, class: 'btn btn-default' %>
</div>

<table cellspacing="0" class="table">
  <tr>
    <th>Title</th>
    <th>Submitted by</th>
    <th>Posted on</th>
    <th>&nbsp;</th>
  </tr>

  <% @posts.each do |p| %>
    <tr>
      <td><%= link_to p.title, post_path(p) %></td>
      <td><%= mail_to p.email, p.author  %></td>
      <td><%= p.created_at.strftime('%a, %m/%d/%y') %></td>
      <td>
        <% form_for :post, :url => post_path(p), method: :destroy do |f| %>
          <%= f.submit 'Delete this post', :confirm => 'Are you sure you want to delete this?' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<div class="pagination">
  <%= will_paginate @posts %>
</div>

app/views/home/about.html.erb
<h1>About GraceList</h1>

<p class="big">GraceList is the community bulletin board system of <a href="http://www.gracepointonline.org" target="_blank">Gracepoint Fellowship Church</a>.  Everyone uses it to make posts and announcements, usually about things that don't warrant an all out email blast to the entire church.  It's simple, straight-forward and just useful to have.</p>

<h2>How it works</h2>
<p class="big">
  The first thing you need to do is to make a new post.  Find an old GraceList email or go to this web page, and click on the <%= link_to 'New Post', new_post_path %> link.  Fill out the information and click <strong>Save</strong>.  Voila, you're done!
</p>

<p class="big">
  GraceList will regularly send out an email to the Gracepoint member aliases notifying folks of posts and announcements.  However, unlike other bulletin board systems that sends out emails regardless of what changes happen, GraceList uses uses something called a <em>digest</em> to collect all the new items that were added that day and send them <strong>all out at once</strong>.  If no new additions are made to GraceList, you're not going to get an email for that day.  <strong>Easy, convenient, and best of all, clutter-free inboxes!</strong>
</p>

<blockquote class="big">Enjoy!<br /> -Your Gracepoint Web Team</blockquote>

<h2>Upcoming Features</h2>
<ul>
  <li>Birthday Reminders</li>
  <li>Church-wide events calendar</li>
</ul>

app/views/home/index.html.erb
<div id="home" class="clearfix">
  <div class="posts">
    <% @categories.each do |c| %>
      <h2><%= c.name %></h2>
      <% c.posts.order('created_at DESC').limit(7).each do |p| %>
        <div class="post clearfix">
          <div class="title"><%= mark_as_new(post_date: p.created_at) %> <%= link_to post_title(p), post_path(p) , :title => p.title %></div>
          <div class="date"><%= time_ago_in_words(p.created_at)  %> ago</div>
        </div>
      <% end %>

      <div class="buttons">
        <%= link_to 'New Post', new_post_path(category_id: c.id) %> |
        <%= link_to "View All #{c.name}", category_path(c) %>
      </div>
    <% end %>
  </div> <!-- end .posts -->
</div> <!-- end #home -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraceList</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'sitewide_css_manifest', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <div class="links">
        <%= link_to 'Home', root_path %> |
        <%= link_to 'About GraceList', about_home_index_path %>
        <div class="emailUpdate">Email updates are sent Monday and Thursdays at 12pm</div>
      </div>
      <div class="title">
        <h1><%= link_to 'GraceList', root_path %></h1>
        <h2>Community Bulletin Board</h2>
      </div>
    </div>

    <div class="container-fluid" id="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <% if @page_title %>
      <h2 class="title"><%= @page_title %></h2>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="post_title">Title<%= required %></label>
    <%= f.text_field 'title', :size => "60", :tabindex => '1', class: 'form-control', placeholder: 'Title'  %>
  </div>

  <div class="form-group">
    <label for="category_id">Category<%= required %></label>
    <%= f.select 'category_id', Category.all.collect {|c| [c.name, c.id] }, :tabindex => '3', class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="post_description">Description<%= required %></label>
    <%= f.text_area 'description', :rows => "14", :cols => "60", :tabindex => '2', class: 'form-control'  %>
  </div>

  <div class="form-group">
    <label for="post_author">Your Name<%= required %></label>
    <%= f.text_field 'author', :tabindex => '4', class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="post_email">Your Email<%= required %></label>
    <%= f.email_field 'email', :tabindex => '5', class: 'form-control' %>
  </div>

  <div class="buttons">
    <%= submit_tag 'Save Post', :tabindex => '6', class: 'btn btn-primary' %> <%= link_to 'Back', root_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<h1>Add a Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="single_post">
  <ol class="breadcrumb">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to @post.category.name, category_path(@post.category) %></li>
  </ol>

  <div class="page-header">
    <h1><%= @post.title %></h1>
    <h3>Posted by <%= mail_to @post.email, @post.author, :subject => "#{@post.title} on GraceList" %> under <%= link_to @post.category.name, category_path(@post.category) %></h3>
    <div class="subtitle">
      <%= time_ago_in_words(@post.created_at) %> ago
    </div>
  </div>

  <div class="description">
    <%= raw @markdown.render(@post.description) %>
  </div>

  <div class="buttons">
    <div class="floatRight">
      <% form_for :post, url: posts_path, method: :delete do |f| %>
        <%= f.submit 'Delete this post', :confirm => 'Are you sure you want to delete this?' %>
      <% end %>
    </div>

    <div class="btn-group" role="group">
      <%= mail_to @post.email, 'Send email to ' + @post.author, :subject => "#{@post.title} on GraceList", class: 'btn btn-default' %>
      <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-default' %>
    </div>

  </div>
</div>